### ISSUE TITLE
Cómo importar acción

### ISSUE THREAD

**Issue by BorjaJajas** [pablolmedorado/filmaffinity-assistant-action#1]
Hola, quería saber cómo puedo importar esta acción a mi cuenta de google, podrías explicármelo paso a paso? Soy novato en esto

**Comment by pablolmedorado** [comment]
Buenas tardes Borja;

En primer lugar, gracias por mostrar interés en mi proyecto.

Respondiendo a tu pregunta, pretendía repasar el repo para refrescar la memoria (el proyecto es del 2019), pero cuando he abierto la Actions Console he visto que no va a ser posible utilizar acciones conversacionales a partir del 13 de junio [de acuerdo a la documentación de Google](https://developers.google.com/assistant/ca-sunset?hl=es-419).

Así las cosas, no tiene sentido que dedique tiempo a echarlo a andar de nuevo.

Lamento lo ocurrido.
Un saludo.

**Comment by BorjaJajas** [comment]
Es una pena. Pues nada, seguro que hay más proyectos interesantes!
